let en = {
  about1: 'We are a small organization of rescuers living in Shanghai, China. We come from all over the world, and met one another through our individual work in the rescue community.',
  about2: 'We are a group of volunteers dedicated to rescuing animals in need, particularly those that are abandoned, abused, neglected, or in danger of being euthanized in Shanghai. Our goal is to find loving, permanent homes for rescued animals and to advocate for animal welfare and responsible pet ownership.',
  filter_tab: 'Filter',
  adopt_btn: 'Favorite',
	share_btn: 'Share',
  about_title: 'About Us',
  text12: 'My Favorites',
  submit: 'Submit',
  cancel: 'Cancel',
  admin_form: 'upload pet info',
  request_tab: 'Activities',
	authorize_button: 'Authorize', 
	contact_button: 'Contact EHR',
	empty_pet: 'Please select another option',
	empty_request: 'You haven\'t favorited any pet yet',
	empty_user: 'You haven\'t received any request yet',
	age: 'Age: ',
	gender: 'Gender: ',
	status: 'Status: ',
	neutered: 'Neutered: ',
	vaccinated: 'Vaccinated: ',
	size: 'Size: ',
	description: 'Description',
	available: 'available',
	unavailable: 'adopted',
	mini: 'mini',
	small: 'small',
	medium: 'medium',
	large: 'large',
  special: 'special need',
  sent_msg: 'Favorited'
}
module.exports = {
  content: en
}