let zh = {
  about1: 'EHRS是一家位于上海的小型动物救援组织。请点击下方卡片了解每个救助故事，收藏并转发，帮助流浪动物找到温暖有爱的家。',
  about2: 'EHRS由来自世界各地的志愿者组成，相信我们的共同努力将为流浪和被遗弃动物的生命和福利带来积极改变。',
  filter_tab: '筛选',
  adopt_btn: '收藏',
	share_btn: '分享',
  about_title: '关于我们',
  text12: '我收藏的',
  submit: '提交',
  cancel: '取消',
  admin_form: '上传动物信息',
  request_tab: '活动记录',
	authorize_button: '点击授权', 
	contact_button: '立即联系我们',
	empty_pet: '请选择其它类型的动物',
	empty_request: '您还没有收藏',
	empty_user: '您还没有收到申请',
	age: '年龄：',
	gender: '性别：',
	status: '寄养或领养：',
	neutered: '绝育：',
	vaccinated: '疫苗：',
	size: '体型：',
	description: '描述',
	both: '都可以',
	adopt_only: '仅领养',
	mini: '迷你',
	small: '小型',
	medium: '中型',
	large: '大型',
  special: '特殊需求',
	sent_msg: '已收藏',
	change: 'English',
	window: '这个宝宝需要您的特殊照顾',
	understand: '明白了'
}

module.exports = {
  content: zh
}
